/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */
 
var cs_debug = true;

//
// Function: load()
// Called by HTML body element's onload event when the widget is ready to start
//
function load()
{  alert("load()");
    dashcode.setupParts();
//    retrievePrefs();
    widget.setPreferenceForKey("constella", "rswID");
    widget.setPreferenceForKey("bear.rsw", "rswPassword");
    widget.setPreferenceForKey("northern6i", "rswGameName");
    document.getElementById("gameDisplay").innerText = "northern6i";
}

//
// Function: remove()
// Called when the widget has been removed from the Dashboard
//
function remove()
{   // Remove preferences
    alert("remove()");
    widget.setPreferenceForKey(null, "rswID");
    widget.setPreferenceForKey(null, "rswPassword");
    widget.setPreferenceForKey(null, "rswGameName");
}

//
// Function: hide()
// Called when the widget has been hidden
//
function hide()
{   alert("hide()");
    // Stop any timers to prevent CPU usage
}

//
// Function: show()
// Called when the widget has been shown
//
function show()
{   alert("show()");
    updateOutstanding();
}

//
// Function: sync()
// Called when the widget has been synchronized with .Mac
//
function sync()
{   alert("sync()");
    // Retrieve any preference values that you need to be synchronized here
    // Use this for an instance key's value:
    // instancePreferenceValue = widget.preferenceForKey(null, dashcode.createInstancePreferenceKey("your-key"));
    //
    // Or this for global key's value:
    // globalPreferenceValue = widget.preferenceForKey(null, "your-key");
}

//
// Function: showBack(event)
// Called when the info button is clicked to show the back of the widget
//
// event: onClick event from the info button
//
function showBack(event)
{   alert("showBack()");
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToBack");
    }

    front.style.display = "none";
    back.style.display = "block";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
        retrievePrefs();
    }
}

//
// Function: showFront(event)
// Called when the done button is clicked from the back of the widget
//
// event: onClick event from the done button
//
function showFront(event)
{   alert("showFront()");
    var front = document.getElementById("front");
    var back = document.getElementById("back");

    if (window.widget) {
        widget.prepareForTransition("ToFront");
        stowPrefs();
        updateOutstanding();
    }

    front.style.display="block";
    back.style.display="none";

    if (window.widget) {
        setTimeout('widget.performTransition();', 0);
    }
}

if (window.widget) {
    widget.onremove = remove;
    widget.onhide = hide;
    widget.onshow = show;
    widget.onsync = sync;
}


function stowPrefs() {
    widget.setPreferenceForKey(idField.value, "rswID");

    // Password is not normally displayed; don't overwrite
    // a valid pw with blanks.  a placeholder would be nice.
    if (passwordField.value && passwordField.value.length > 0) {
        widget.setPreferenceForKey(passwordField.value, "rswPassword");
        passwordField.value = "";  // clear so secret not revealed in future.
    }

    widget.setPreferenceForKey(gameField.value, "rswGameName");
    
    // Set the fields on the front & update everything
    document.getElementById("gameDisplay").innerText = gameField.value;
    document.getElementById("turnsDisplay").innerText = "--";
}


function retrievePrefs() {
    var idPref = widget.preferenceForKey("rswID"); 
    if (idPref && idPref.length > 0) {
        idField.value = idPref;
    }

    var gamePref = widget.preferenceForKey("rswGameName"); 
    if (gamePref && gamePref.length > 0) {
        gameField.value = gamePref;
    }    
}

function updateOutstanding() {
    var postDataString = postData();
    if ("" == postDataString) {
        statusMessage.innerText =
        "Please fill in id, password, and game on the back.";
        return;
    }

    statusMessage.innerText = "... updating ...";
    statusIndicator.object.setValue(10);
    retrieveGameStatus(postDataString);
}

function retrieveGameStatus(postDataString) {
    alert("retrieveGameStatus() " + cs_debug);
    if (!cs_debug) {
        alert("get real server response");
        $.ajax({
            type: "POST",
            url: "https://rswgame.com/xml",
            cache: false,
            processData: false,
            data: postDataString,
            success: function(data){ processGames(data); },
            contentType: "text/xml",
            dataType: "xml"
        });
    }
    else {  // get mock response
        alert("process mock response");
        processGames("<?xml version='1.0' encoding='utf-8'?><response><gameHeader gameId='northern6i' numWaitingFor='6' state='active'/></response>");
    }

}

function postData() {
    var idPref = widget.preferenceForKey("rswID");
    var gamePref = widget.preferenceForKey("rswGameName");
    var passPref = widget.preferenceForKey("rswPassword");
    
    if (idPref && idPref.length > 0 &&
        gamePref && gamePref.length > 0 &&
        passPref && passPref.length > 0) {
        return "<?xml version='1.0'?>" +
            "<request command='list'>" + 
            "<parameter keyword='accountId' value='" +
            idPref + "' />" + 
            "<parameter keyword='password' value='" + 
            passPref + "' />" + 
            "<parameter keyword='onlyMine' value='true' />" +
            "<parameter keyword='format' value='xml' />" +
            "<parameter keyword='active' value='true' />" +
            "</request>";
    }
    else {
        return "";
    }
}

function processGames(game_xml) {
    // presume things will succeed
    statusMessage.innerText = "";
    statusIndicator.object.setValue(1);  
    
    var rgame = widget.preferenceForKey("rswGameName");
    var result = "";
    
    $(game_xml).find("gameHeader").each(function() {
        var header = $(this);
        if (header.attr("gameId") == rgame) {
            result = header.attr("numWaitingFor");
        }
    });
        
    if (result == "") {
        statusIndicator.object.setValue(15);
        statusMessage.innerText = "game not found or inactive";
    }
    else {
        turnsDisplay.innerText = result;
    }
}



function clickDebug(event)
{
    widget.openURL("mailto:bugs@constella.org?subject=xml log&body=something went really really wrong.");
}

function clickFeedback(event)
{
    widget.openURL("http://constella.uservoice.com/");
}